config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :employees

  resources :invoices

  resources :diagnostic_codes

  resources :physicians

  resources :employeeemployee_ids

  resources :insurances

  resources :patients

  root 'home#dashboard'

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_many :invoices

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_id, :first_name, :last_name, :phone, :email, :dob, :sex, :address, :city, :state, :zip, :emergency_contact, :relation, :emergency_contact_number, :insurance_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :emergency_contact %><br>
    <%= f.text_field :emergency_contact %>
  </div>
  <div class="field">
    <%= f.label :relation %><br>
    <%= f.text_field :relation %>
  </div>
  <div class="field">
    <%= f.label :emergency_contact_number %><br>
    <%= f.text_field :emergency_contact_number %>
  </div>
  <div class="field">
    <%= f.label :insurance_id %><br>
    <%= f.collection_select( :insurance_id, Insurance.all, :id, :insurance_name, :prompt => "Select Insurance")%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<div class="media" >

  <div class="media-body">
    <table class="table table-hover">

  <thead>
    <tr>
      <th>Employee</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Sex</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Emergency contact</th>
      <th>Relation</th>
      <th>Emergency contact number</th>
      <th>Insurance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>

        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.email %></td>
        <td><%= employee.dob %></td>
        <td><%= employee.sex %></td>
        <td><%= employee.address %></td>
        <td><%= employee.city %></td>
        <td><%= employee.state %></td>
        <td><%= employee.zip %></td>
        <td><%= employee.emergency_contact %></td>
        <td><%= employee.relation %></td>
        <td><%= employee.emergency_contact_number %></td>
        <td><%= employee.insurance_id %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
    </div>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @employee.dob %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @employee.sex %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employee.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @employee.zip %>
</p>

<p>
  <strong>Emergency contact:</strong>
  <%= @employee.emergency_contact %>
</p>

<p>
  <strong>Relation:</strong>
  <%= @employee.relation %>
</p>

<p>
  <strong>Emergency contact number:</strong>
  <%= @employee.emergency_contact_number %>
</p>

<p>
  <strong>Insurance:</strong>
  <%= @employee.insurance_id %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>